### PR TITLE
NVLI-202 : Create Resource Entity for NVLI

### PR DESCRIPTION
**Pull request by ashishdalvi**
Task completed : 
1. Created a content type "Resource". 
2. Fields as per document: http://www.cse.iitb.ac.in/confluence/display/DND/Resource+Entity+for+NVLI
3. Exported content type and respective changes using features.
4. Enable feature "Resource" to avail content type and its configuration.

### CODE REVIEW

**Comment by ashishdalvi** [comment]
Hi @piyuesh23 ,

I am working on adding new fields to resource content type. 
Please do not review pull request now.  I will update it.

Thanks

**Comment by ashishdalvi** [comment]
@piyuesh23 : 
My commits are as follows :     de4ba0f, 834fd83,  d0087b4, 3747593, 9cfecef

Its seems other commits also got pulled in this request due to local merge of dev branch in NVLI-202.  Commit ID : [4cd5df4](https://github.com/NVLI/nvli-main-website/pull/12/commits/4cd5df4ae1ea371b55c71d0eaccf827e64e3b2aa)

Implementation Steps 
1. Enable `features` and `Feature UI` module
2. Enable `resource` module
3. **Resource** content type will get created with respective fields 
http://www.cse.iitb.ac.in/confluence/display/DND/Resource+Entity+for+NVLI

**Comment by piyuesh23** [comment]
@ashishdalvi This is not mergeable. Can you fix up the merge conflicts.

**Comment by ashishdalvi** [comment]
Merge conflict resolved. Please review.

**Comment by piyuesh23** [comment]
@ashishdalvi 

Few comments:
- docroot/sites/default/sync: Were the files in this directory added explicitly? Do we need to import it?
- docroot/modules/features: Are we introducing features module? Or is this something added as a dependency to another module. Can you specify which module in the later case?

**Comment by ashishdalvi** [comment]
- docroot/sites/default/sync : I have exported this configuration using `drush config-export`. Yes Importing this file will enable default settings of website
- Features : Yes, We are using features module directly to export configuration. Resource content type and its respective configuration has been captured using features module.

**Comment by piyuesh23** [comment]
@ashishdalvi Can you resolve the merge conflict & update this PR.

**Comment by ashishdalvi** [comment]
@piyuesh23 : Resolved merge conflict.

**Pull request merged**
